language: node_js
node_js:
  - 0.10
notifications:
  email:
    recipients:
      - ikaduu@gmail.com
      - carloseduardolbraz@gmail.com
    on_success: [always|never|change] # default: always
    on_failure: [always|never|change] # default: always
